### ISSUE TITLE
training test shows filenotfounderror of benchmark/set5

### ISSUE THREAD

**Issue by Estella12** [zhengchen1999/DAT#17]
Running train.py in pycharm, shows filenotfounderror in datasets/benchmark/Set5/...
Readme  says set5 is for test, so is the data needed in training process? 
thx

**Comment by zhengchen1999** [comment]
The Set5 dataset is used to verify during training that everything is proceeding normally. It's just for monitoring the training trend of the model and does not participate in model selection.

**Comment by Estella12** [comment]
ok, is there a download link on the cloud drive for mainland? 
thx

**Comment by zhengchen1999** [comment]
@Estella12 We have released the download link of Baidu Disk at [here](https://github.com/zhengchen1999/DAT#datasets).

**Comment by Estella12** [comment]
thx
