### ISSUE TITLE
"No object named 'DATModle' found in 'model' registry!"

### ISSUE THREAD

**Issue by nickhdfan** [zhengchen1999/DAT#6]
C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Disable distributed.
Path already exists. Rename it to C:\Executables\DAT-main\results\test_single_x4_archived_20230822_211914
2023-08-22 21:19:14,914 INFO:
  name: test_single_x4
  model_type: DATModle
  scale: 4
  num_gpu: 1
  manual_seed: 10
  datasets:[
    test_1:[
      name: Single
      type: SingleImageDataset
      dataroot_lq: datasets/single
      io_backend:[
        type: disk
      ]
      phase: test
      scale: 4
    ]
  ]
  network_g:[
    type: DAT
    upscale: 4
    in_chans: 3
    img_size: 64
    img_range: 1.0
    split_size: [8, 32]
    depth: [6, 6, 6, 6, 6, 6]
    embed_dim: 180
    num_heads: [6, 6, 6, 6, 6, 6]
    expansion_factor: 4
    resi_connection: 1conv
  ]
  path:[
    pretrain_network_g: experiments/pretrained_models/DAT/DAT_x4.pth
    strict_load_g: True
    results_root: C:\Executables\DAT-main\results\test_single_x4
    log: C:\Executables\DAT-main\results\test_single_x4
    visualization: C:\Executables\DAT-main\results\test_single_x4\visualization
  ]
  val:[
    save_img: True
    suffix: x4
    use_chop: True
  ]
  dist: False
  rank: 0
  world_size: 1
  auto_resume: False
  is_train: False

2023-08-22 21:19:14,914 INFO: Dataset [SingleImageDataset] - Single is built.
2023-08-22 21:19:14,914 INFO: Number of test images in Single: 1
Name DATModle is not found, use name: DATModle_basicsr!
Traceback (most recent call last):
  File "basicsr/test.py", line 44, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 34, in test_pipeline
    model = build_model(opt)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\basicsr\models\__init__.py", line 26, in build_model
    model = MODEL_REGISTRY.get(opt['model_type'])(opt)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python38\lib\site-packages\basicsr\utils\registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'DATModle' found in 'model' registry!"

**Comment by nickhdfan** [comment]
any idea what I did wrong?

**Comment by zhengchen1999** [comment]
I think your error is because [Dependencies](https://github.com/zhengchen1999/DAT#dependencies) are not prepared. You can refer to another [issue](https://github.com/zhengchen1999/DAT/issues/1).

By the way, do other command other run successfully?

**Comment by nickhdfan** [comment]
It's working now, I copied basicsr folder from DAT to locally installed basicsr

**Comment by buhuiya** [comment]
> It's working now, I copied basicsr folder from DAT to locally installed basicsr without replacing any file (only copy new file)
May I ask how it is operated specifically？

**Comment by buhuiya** [comment]
> It's working now, I copied basicsr folder from DAT to locally installed basicsr without replacing any file (only copy new file)


May I ask how it is operated specifically
